### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by cashweaver-zz** [cbweaver/cms-manager#5]
Backup a website:
- Files
- Database

**Comment by cashweaver-zz** [comment]
Intended functionality:
1. Attempt to save database and files to backups directory. Backups directory will be set by command line.
2. In the event either database or file backup fail, return an error and alert the user.
3. If everything went well, print a success message and return with no errors.

**Comment by cbweaver** [comment]
Potential errors:* Error writing database backup
